name: Release Build
on:
  push:
    tags: ["*"]
  workflow_dispatch:
    inputs:
      version:
        description: "版本号 (例如: v1.0.0)"
        required: true
        default: "dev-build"

jobs:
  build-linux-x64:
    runs-on: ubuntu
    container:
      image: git.fig-lang.cn/puqiar/fig-ci:base-latest
      options: --network=host

    steps:
      - name: 验证构建环境
        run: |
          echo "=== 环境验证开始 ==="
          xmake --version
          clang++ --version | head -1
          echo "=== 环境验证通过 ==="

      - name: 检出代码
        run: |
          git clone https://git.fig-lang.cn/${{ github.repository }} .
          git checkout ${{ github.ref }}

      - name: 设置版本
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            VERSION="${{ inputs.version }}"
          else
            VERSION="${GITHUB_REF#refs/tags/}"
          fi
          echo "构建版本: $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: 构建项目 (Linux)
        run: |
          echo "开始构建Linux版本..."
          xmake f -p linux -a x86_64 -m release -y
          xmake build -j$(nproc)
          echo "Linux构建成功。"

      - name: 打包Linux发布文件
        run: |
          PACKAGE_NAME="Fig-${{ env.VERSION }}-linux-x86_64"
          mkdir -p "${PACKAGE_NAME}"
          cp build/linux/x86_64/release/Fig "${PACKAGE_NAME}/"
          if [ -d "src/Module/Library" ]; then
            cp -r src/Module/Library "${PACKAGE_NAME}/"
            echo "已包含Library目录。"
          fi
          tar -czf "${PACKAGE_NAME}.tar.gz" "${PACKAGE_NAME}"
          sha256sum "${PACKAGE_NAME}.tar.gz" > "${PACKAGE_NAME}.sha256"
          echo "Linux打包完成: ${PACKAGE_NAME}.tar.gz"

      - name: 发布Linux版本到Gitea
        env:
          GITEA_TOKEN: ${{ secrets.CI_TOKEN }}
        run: |
          VERSION="${{ env.VERSION }}"
          API="https://git.fig-lang.cn/api/v1/repos/${{ github.repository }}"
          
          echo "正在为Linux版本创建/更新发布 $VERSION ..."
          
          RESPONSE=$(curl -sS -X POST -H "Authorization: token $GITEA_TOKEN" \
            -H "Content-Type: application/json" \
            -d "{\"tag_name\":\"$VERSION\",\"name\":\"Fig $VERSION\",\"draft\":false,\"prerelease\":false}" \
            "$API/releases" 2>/dev/null || echo '{"id":0}')
          
          RELEASE_ID=$(echo "$RESPONSE" | grep -o '"id":[0-9]*' | head -1 | cut -d':' -f2)
          
          if [ -z "$RELEASE_ID" ] || [ "$RELEASE_ID" = "0" ]; then
            echo "尝试通过标签获取已有发布的ID..."
            RELEASE_ID=$(curl -sS -H "Authorization: token $GITEA_TOKEN" \
              "$API/releases/tags/$VERSION" | grep -o '"id":[0-9]*' | head -1 | cut -d':' -f2)
          fi
          
          if [ -z "$RELEASE_ID" ]; then
            echo "错误：无法获取或创建发布 ID"
            exit 1
          fi
          
          echo "使用发布 ID: $RELEASE_ID 进行上传"
          
          curl -sS -X POST -H "Authorization: token $GITEA_TOKEN" \
            -H "Content-Type: application/octet-stream" \
            --data-binary @Fig-$VERSION-linux-x86_64.tar.gz \
            "$API/releases/$RELEASE_ID/assets?name=Fig-$VERSION-linux-x86_64.tar.gz"
          
          curl -sS -X POST -H "Authorization: token $GITEA_TOKEN" \
            -H "Content-Type: text/plain" \
            --data-binary @Fig-$VERSION-linux-x86_64.sha256 \
            "$API/releases/$RELEASE_ID/assets?name=Fig-$VERSION-linux-x86_64.sha256"
          
          echo "✅ Linux版本发布完成！"

  build-windows-x64:
    runs-on: windows

    steps:
      - name: 验证Windows工具链
        run: |
          # 设置当前 PowerShell 会话的执行策略
          powershell -Command "Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope Process -Force"
          
          # 使用 PowerShell 语法检查工具链
          powershell -Command "
            # 检查 xmake
            if (Get-Command xmake -ErrorAction SilentlyContinue) {
              Write-Host '✅ xmake 已安装'
              xmake --version
            } else {
              Write-Host '警告: xmake 未找到'
            }
            
            # 检查 clang++
            if (Get-Command clang++ -ErrorAction SilentlyContinue) {
              Write-Host '✅ clang++ 已安装'
              clang++ --version
            } else {
              Write-Host '警告: clang++ 未找到'
            }
            
            # 检查 git（可选）
            if (Get-Command git -ErrorAction SilentlyContinue) {
              Write-Host '✅ git 已安装'
            } else {
              Write-Host '警告: git 未找到'
            }
          "

      - name: 检出代码
        run: |
          # 确保Git在PATH中
          $env:Path = "C:\Program Files\Git\cmd;$env:Path"
          git clone https://git.fig-lang.cn/${{ github.repository }} .
          git checkout ${{ github.ref }}

      - name: 设置版本
        run: |
          # 方法：通过 Gitea 预置的环境变量获取所有信息
          $EventName = $env:GITHUB_EVENT_NAME
          $Ref = $env:GITHUB_REF
          $RefName = $env:GITHUB_REF_NAME # 这是标签名或分支名
          
          Write-Host "事件类型: $EventName"
          Write-Host "引用: $Ref"
          Write-Host "引用名称: $RefName"
          
          if ($EventName -eq 'workflow_dispatch') {
            # 手动触发：从输入获取版本
            # Gitea 通常会把 inputs.xxx 转为 INPUT_XXX 环境变量
            $VERSION = $env:INPUT_VERSION
            if (-not $VERSION) {
              # 如果环境变量名不同，尝试其他常见名称
              $VERSION = $env:VERSION
              if (-not $VERSION) {
                $VERSION = "dev-build"
              }
            }
          } else {
            # 标签推送：直接从引用名称获取
            $VERSION = $RefName
          }
          
          Write-Host "构建版本: $VERSION"
          echo "VERSION=$VERSION" >> $env:GITHUB_ENV
      - name: 构建项目 (Windows Native)
        run: |
          powershell -Command "
            xmake f -p windows -p mingw -a x86_64 -m release -y
            xmake build -j`$env:NUMBER_OF_PROCESSORS
            Write-Host 'Windows构建成功。'
          "

      - name: 打包Windows发布文件
        run: |
          powershell -Command "
            `$VERSION = `$env:VERSION
            `$PACKAGE_NAME = \"Fig-`$VERSION-windows-x86_64\"
            New-Item -ItemType Directory -Force -Path `$PACKAGE_NAME
            
            # 尝试查找可执行文件
            if (Test-Path 'build\windows\x86_64\release\Fig.exe') {
              Copy-Item 'build\windows\x86_64\release\Fig.exe' `$PACKAGE_NAME\
            } elseif (Test-Path 'build\windows\x86_64\release\Fig') {
              Copy-Item 'build\windows\x86_64\release\Fig' `$PACKAGE_NAME\Fig.exe
            } else {
              Write-Host '错误：未找到构建输出文件'
              Get-ChildItem -Recurse -Path build -Include 'Fig*' | Select-Object -First 5
              exit 1
            }
            
            if (Test-Path 'src\Module\Library') {
              Copy-Item -Recurse 'src\Module\Library' `$PACKAGE_NAME\
            }
            Compress-Archive -Path `$PACKAGE_NAME -DestinationPath \"`$PACKAGE_NAME.zip\"
            Get-FileHash \"`$PACKAGE_NAME.zip\" -Algorithm SHA256 | Out-File \"`$PACKAGE_NAME.sha256\" -Encoding UTF8
            Write-Host \"Windows打包完成: `$PACKAGE_NAME.zip\"
          "

      - name: 发布Windows版本到Gitea
        env:
          GITEA_TOKEN: ${{ secrets.CI_TOKEN }}
        run: |
          powershell -Command "
            `$VERSION = `$env:VERSION
            `$API = 'https://git.fig-lang.cn/api/v1/repos/${{ github.repository }}'
            
            Write-Host \"正在上传Windows版本到发布 `$VERSION ...\"
            
            # 1. 尝试通过标签获取 Release ID
            `$RELEASE_RESPONSE = Invoke-RestMethod -Uri \"`$API/releases/tags/`$VERSION\" -Headers @{
              Authorization = \"token `$env:GITEA_TOKEN\"
            } -ErrorAction SilentlyContinue
            
            if (`$RELEASE_RESPONSE -and `$RELEASE_RESPONSE.id) {
              `$RELEASE_ID = `$RELEASE_RESPONSE.id
              Write-Host \"找到已有发布 ID: `$RELEASE_ID\"
            } else {
              # 如果不存在，则创建新发布
              Write-Host '发布不存在，正在创建...'
              `$CREATE_BODY = @{
                tag_name = `$VERSION
                name = \"Fig `$VERSION\"
                draft = `$false
                prerelease = `$false
              } | ConvertTo-Json
              
              `$CREATE_RESPONSE = Invoke-RestMethod -Method Post -Uri \"`$API/releases\" -Headers @{
                Authorization = \"token `$env:GITEA_TOKEN\"
                'Content-Type' = 'application/json'
              } -Body `$CREATE_BODY -ErrorAction SilentlyContinue
              
              if (`$CREATE_RESPONSE -and `$CREATE_RESPONSE.id) {
                `$RELEASE_ID = `$CREATE_RESPONSE.id
                Write-Host \"创建新发布 ID: `$RELEASE_ID\"
              } else {
                Write-Host '错误：无法获取或创建发布'
                exit 1
              }
            }
            
            # 2. 使用 Release ID 上传资产
            Write-Host '正在上传 ZIP 文件...'
            Invoke-RestMethod -Method Post -Uri \"`$API/releases/`$RELEASE_ID/assets?name=Fig-`$VERSION-windows-x86_64.zip\" -Headers @{
              Authorization = \"token `$env:GITEA_TOKEN\"
              'Content-Type' = 'application/octet-stream'
            } -InFile \"Fig-`$VERSION-windows-x86_64.zip\" -ErrorAction SilentlyContinue
            
            Write-Host '正在上传校验文件...'
            Invoke-RestMethod -Method Post -Uri \"`$API/releases/`$RELEASE_ID/assets?name=Fig-`$VERSION-windows-x86_64.sha256\" -Headers @{
              Authorization = \"token `$env:GITEA_TOKEN\"
              'Content-Type' = 'text/plain'
            } -InFile \"Fig-`$VERSION-windows-x86_64.sha256\" -ErrorAction SilentlyContinue
            
            Write-Host '✅ Windows版本发布完成！'
          "